import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import pg from 'pg';

const app = express();
const port = process.env.PORT || 3000;
const pool = process.env.DATABASE_URL ? new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }) : null;
const allowedOrigins = (process.env.CORS_ORIGIN || '').split(',').map(origin => { try { return new URL(origin.trim()).origin; } catch { return origin.trim().replace(/\/$/, ''); } }).filter(Boolean);
app.use(cors({ origin: (origin, callback) => !origin || !allowedOrigins.length || allowedOrigins.includes(origin) ? callback(null, true) : callback(new Error('CORS origin not allowed')) }));
app.use(express.json());

const queries = {
  classes: `SELECT c.*, t.full_name AS teacher_name, COUNT(s.student_id)::int AS student_count FROM classes c LEFT JOIN teachers t ON t.teacher_id = c.teacher_id LEFT JOIN students s ON s.class_id = c.class_id GROUP BY c.class_id, t.full_name`,
  teachers: `SELECT t.*, c.class_name, c.class_code FROM teachers t LEFT JOIN classes c ON c.teacher_id = t.teacher_id`,
  students: `SELECT s.*, c.class_name, c.class_code FROM students s JOIN classes c ON c.class_id = s.class_id`
};
const requireDb = (request, response, next) => pool ? next() : response.status(503).json({ error: 'Database is not configured. Set DATABASE_URL on the API.' });
const sendError = (response, error) => response.status(error.code === '23505' ? 409 : 400).json({ error: error.code === '23505' ? 'That code or email is already in use.' : error.message });

app.get('/api/health', (_request, response) => response.json({ status: 'ok' }));
app.get('/api/db-check', requireDb, async (_request, response) => { try { const result = await pool.query('SELECT NOW() AS database_time'); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });

app.get('/api/classes', requireDb, async (_request, response) => { try { response.json((await pool.query(`${queries.classes} ORDER BY c.class_id`)).rows); } catch (error) { sendError(response, error); } });
app.get('/api/classes/:id', requireDb, async (request, response) => { try { const result = await pool.query(`${queries.classes} HAVING c.class_id = $1`, [request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Class not found.' }); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.post('/api/classes', requireDb, async (request, response) => { try { const { class_code, class_name, subjects, schedule_days, schedule_time, room, teacher_id, status = 'Active' } = request.body; if (!class_code || !class_name) return response.status(400).json({ error: 'Class code and name are required.' }); const result = await pool.query('INSERT INTO classes (class_code,class_name,subjects,schedule_days,schedule_time,room,teacher_id,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *', [class_code, class_name, subjects, schedule_days, schedule_time, room, teacher_id || null, status]); response.status(201).json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.put('/api/classes/:id', requireDb, async (request, response) => { try { const { class_code, class_name, subjects, schedule_days, schedule_time, room, teacher_id, status } = request.body; const result = await pool.query('UPDATE classes SET class_code=$1,class_name=$2,subjects=$3,schedule_days=$4,schedule_time=$5,room=$6,teacher_id=$7,status=$8 WHERE class_id=$9 RETURNING *', [class_code, class_name, subjects, schedule_days, schedule_time, room, teacher_id || null, status, request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Class not found.' }); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.delete('/api/classes/:id', requireDb, async (request, response) => { try { const count = await pool.query('SELECT COUNT(*)::int AS count FROM students WHERE class_id=$1', [request.params.id]); if (count.rows[0].count) return response.status(409).json({ error: 'This class still has students. Reassign them before deleting it.' }); const result = await pool.query('DELETE FROM classes WHERE class_id=$1 RETURNING class_id', [request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Class not found.' }); response.status(204).end(); } catch (error) { sendError(response, error); } });

app.get('/api/teachers', requireDb, async (_request, response) => { try { response.json((await pool.query(`${queries.teachers} ORDER BY t.teacher_id`)).rows); } catch (error) { sendError(response, error); } });
app.get('/api/teachers/:id', requireDb, async (request, response) => { try { const result = await pool.query(`${queries.teachers} OFFSET 0`, []); const teacher = result.rows.find(item => String(item.teacher_id) === request.params.id); if (!teacher) return response.status(404).json({ error: 'Teacher not found.' }); response.json(teacher); } catch (error) { sendError(response, error); } });
app.post('/api/teachers', requireDb, async (request, response) => { try { const { teacher_code, full_name, email, phone, subject_specialty, join_date, status = 'Active' } = request.body; if (!teacher_code || !full_name || !email) return response.status(400).json({ error: 'Teacher code, name, and email are required.' }); if (!/^\S+@\S+\.\S+$/.test(email)) return response.status(400).json({ error: 'Enter a valid email address.' }); const result = await pool.query('INSERT INTO teachers (teacher_code,full_name,email,phone,subject_specialty,join_date,status) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [teacher_code, full_name, email, phone, subject_specialty, join_date || null, status]); response.status(201).json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.put('/api/teachers/:id', requireDb, async (request, response) => { try { const { teacher_code, full_name, email, phone, subject_specialty, join_date, status } = request.body; const result = await pool.query('UPDATE teachers SET teacher_code=$1,full_name=$2,email=$3,phone=$4,subject_specialty=$5,join_date=$6,status=$7 WHERE teacher_id=$8 RETURNING *', [teacher_code, full_name, email, phone, subject_specialty, join_date || null, status, request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Teacher not found.' }); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.delete('/api/teachers/:id', requireDb, async (request, response) => { try { const result = await pool.query('DELETE FROM teachers WHERE teacher_id=$1 RETURNING teacher_id', [request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Teacher not found.' }); response.status(204).end(); } catch (error) { sendError(response, error); } });

app.get('/api/students', requireDb, async (request, response) => { try { const query = request.query.class_id ? `${queries.students} WHERE s.class_id=$1 ORDER BY s.student_id` : `${queries.students} ORDER BY s.student_id`; response.json((await pool.query(query, request.query.class_id ? [request.query.class_id] : [])).rows); } catch (error) { sendError(response, error); } });
app.get('/api/students/:id', requireDb, async (request, response) => { try { const result = await pool.query(`${queries.students} WHERE s.student_id=$1`, [request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Student not found.' }); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.post('/api/students', requireDb, async (request, response) => { try { const { student_code, full_name, gender, age, class_id, guardian_name, guardian_phone, guardian_email, enrolment_date, status = 'Active' } = request.body; if (!student_code || !full_name || !class_id || !guardian_name) return response.status(400).json({ error: 'Code, name, class, and guardian are required.' }); const result = await pool.query('INSERT INTO students (student_code,full_name,gender,age,class_id,guardian_name,guardian_phone,guardian_email,enrolment_date,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *', [student_code, full_name, gender, age || null, class_id, guardian_name, guardian_phone, guardian_email, enrolment_date || null, status]); response.status(201).json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.put('/api/students/:id', requireDb, async (request, response) => { try { const { student_code, full_name, gender, age, class_id, guardian_name, guardian_phone, guardian_email, enrolment_date, status } = request.body; const result = await pool.query('UPDATE students SET student_code=$1,full_name=$2,gender=$3,age=$4,class_id=$5,guardian_name=$6,guardian_phone=$7,guardian_email=$8,enrolment_date=$9,status=$10 WHERE student_id=$11 RETURNING *', [student_code, full_name, gender, age || null, class_id, guardian_name, guardian_phone, guardian_email, enrolment_date || null, status, request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Student not found.' }); response.json(result.rows[0]); } catch (error) { sendError(response, error); } });
app.delete('/api/students/:id', requireDb, async (request, response) => { try { const result = await pool.query('DELETE FROM students WHERE student_id=$1 RETURNING student_id', [request.params.id]); if (!result.rowCount) return response.status(404).json({ error: 'Student not found.' }); response.status(204).end(); } catch (error) { sendError(response, error); } });

app.use((_request, response) => response.status(404).json({ error: 'Route not found.' }));
app.listen(port, () => console.log(`Sunrise API listening on port ${port}`));
